// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2e2I-R3PKmX7SYTrLium2LAniXsFYZB8',
    appId: '1:874554314720:web:6ca19740728519bb396585',
    messagingSenderId: '874554314720',
    projectId: 'alien-baton-362106',
    authDomain: 'alien-baton-362106.firebaseapp.com',
    storageBucket: 'alien-baton-362106.appspot.com',
    measurementId: 'G-2MFHGJD46H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdkLQA26iOLbH9qYbiFZLaiPpEWrVRuds',
    appId: '1:874554314720:android:79c478435bae7eea396585',
    messagingSenderId: '874554314720',
    projectId: 'alien-baton-362106',
    storageBucket: 'alien-baton-362106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaFkHTMgkjvXh3sHFAmNGaRimXgngwwnY',
    appId: '1:874554314720:ios:a5316dcfad9e5dc8396585',
    messagingSenderId: '874554314720',
    projectId: 'alien-baton-362106',
    storageBucket: 'alien-baton-362106.appspot.com',
    iosClientId: '874554314720-6r80fnp6gqhui787a0hltkvte5hkvd19.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaFkHTMgkjvXh3sHFAmNGaRimXgngwwnY',
    appId: '1:874554314720:ios:a70fc5952ff4bc8d396585',
    messagingSenderId: '874554314720',
    projectId: 'alien-baton-362106',
    storageBucket: 'alien-baton-362106.appspot.com',
    iosClientId: '874554314720-i7pad83jq1rci481sfb3vj8s2egbl9b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
